---

## - name: Add node to consul cluster
##   shell: consul join {{ consul_master_ip }}
##   when: consul_master_ip|default(false)
## 
## - name: Create consul check definitions
##   template: src=consul_check.json.j2 dest={{ consul_conf_dir }}/consul_check.json
##   register: result
## 
## - name: Restart consul
##   shell: killall -HUP consul
##   when: result|changed
## 
## - name: Run registrator
##   docker:
##     name: registrator
##     volumes:
##       - /var/run/docker.sock:/tmp/docker.sock
##     hostname: "{{ ansible_hostname }}"
##     image: gliderlabs/registrator
##     command: "-ip {{ consul_bind_ip }} consul://{{ consul_bind_ip }}:8500"
## 
## - name: Registrator KV is running
##   docker:
##     name: registrator-kv
##     volumes:
##       - /var/run/docker.sock:/tmp/docker.sock
##     hostname: "{{ ansible_hostname }}"
##     image: gliderlabs/registrator
##     command: "-ip {{ consul_bind_ip }} consulkv://{{ consul_bind_ip }}:8500/services"

